accounts/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^login/$', views.user_login, name='user_login'),
    url(r'^logout/$', views.user_logout, name='user_logout'),
    url(r'^register/$', views.user_register, name='user_register'),
    url(r'^change_password/$', views.change_password, name='change_password'),
]

todo/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # url(r'^login/$', views.user_login, name='user_login'),
    # url(r'^logout/$', views.user_logout, name='user_logout'),
    # url(r'^register/$', views.user_register, name='user_register'),
    url(r'^edit/(\d+)/$', views.edit_todo, name='edit_todo'),
    url(r'^create/$', views.create_todo, name='create_todo'),
    url(r'^details/(\d+)/$', views.todo_details, name='todo_details'),
    # url(r'^changepass/$', views.change_password, name='change_password'),
]

todo_list/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^todo/', include('todo.urls', namespace='todo')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms


# Login form
class LoginForm(forms.Form):
    username = forms.CharField(label='Username:', max_length=100)
    password = forms.CharField(label='Password:', widget=forms.PasswordInput())


# Register form
class RegisterForm(forms.Form):
    username = forms.CharField(label="Username:", max_length=100)
    email = forms.CharField(label="Email")
    password = forms.CharField(label="Password:", widget=forms.PasswordInput())
    re_password = forms.CharField(label="Re-enter password:", widget=forms.PasswordInput())


# Change password form
class ChangePasswordForm(forms.Form):
    current_password = forms.CharField(label="Current password:", widget=forms.PasswordInput())
    new_password = forms.CharField(label="Enter new password:", widget=forms.PasswordInput())
    re_password = forms.CharField(label="Re-enter new password:", widget=forms.PasswordInput())

accounts/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, views
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.hashers import check_password

from .forms import LoginForm, RegisterForm, ChangePasswordForm


def user_login(request):
    """Log user in"""
    message = ''
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        # if form data is valid
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']

            user = authenticate(username=username, password=password)
            # if user is authenticated successfully
            if user is not None:
                # and the account is active
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect('/todo/')
                else:
                    message = 'Account is disabled.'
            else:
                message = 'Incorrect username or password.'

    else:
        login_form = LoginForm()

    return render(request, 'accounts/login.html', {
        'login_form': login_form,
        'message': message,
    })


@login_required
def user_logout(request):
    """Log a user out"""
    return views.logout(request, next_page='/todo/', template_name='accounts/login.html')


def user_register(request):
    """Register a new user"""

    message = ''

    if request.method == 'POST':
        register_form = RegisterForm(request.POST)

        if register_form.is_valid():
            username = register_form.cleaned_data['username']
            email = register_form.cleaned_data['email']
            password = register_form.cleaned_data['password']
            re_password = register_form.cleaned_data['re_password']

            user_list = User.objects.all()
            username_list = [user.username for user in user_list]
            email_list = [user.email for user in user_list]

            # Check for a mountain of conditions
            if username in username_list:
                message = 'Username already taken.'
            elif not username:
                message = 'Username can not be empty.'
            elif email == '':
                message = 'Email is required.'
            elif email in email_list:
                message = 'Email already taken.'
            elif password != re_password:
                message = 'Passwords do not match.'
            else:
                newuser = User(username=username, email=email)
                newuser.set_password(password)
                newuser.save()
                return HttpResponseRedirect('/todo/')
    else:
        register_form = RegisterForm()

    return render(request, 'accounts/register.html', {
        'message': message,
        'register_form': register_form,
    })


@login_required
def change_password(request):
    """Change user's password"""

    message = ''

    if request.method == 'POST':
        current_user = request.user
        change_pass_form = ChangePasswordForm(request.POST)

        if change_pass_form.is_valid():
            new_password = change_pass_form.cleaned_data['new_password']
            re_password = change_pass_form.cleaned_data['re_password']
            current_password = change_pass_form.cleaned_data['current_password']

            if not check_password(current_password, current_user.password):
                message = "Current password is incorrect."
            else:
                if new_password == re_password:
                    current_user.set_password(new_password)
                    current_user.save()
                    message = 'Your password has been changed.'

                    return render(request, 'accounts/change_password_success.html', {
                        'message': message
                    })
                else:
                    message = 'Passwords do not match.'
    else:
        change_pass_form = ChangePasswordForm()

    return render(request, 'accounts/change_password.html', {
        'message': message,
        'change_pass_form': change_pass_form,
    })

accounts/templates/accounts/change_password.html
{% extends 'todo/_base.html' %}
{% load widget_tweaks %}

{% block body %}

	<h3 class="text-center"> <strong>Change Password</strong> </h3> <br>

	<form action="{% url 'accounts:change_password' %}" method="post">
		{% csrf_token %}

		{% include "todo/form_snippet.html" with form=change_pass_form %}

    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4">
        {% if message %}
          <div id="message">
            <strong> {{ message }} </strong>
          </div>
        {% endif %} 
      </div>
      <div class="col-md-4"></div>
    </div><br>

		<div class="text-center">
			<input type="submit" value="Change password" class="btn btn-primary">
		</div>
	
	</form>

{% endblock %}

accounts/templates/accounts/change_password_success.html
{% extends 'todo/_base.html' %}

{% block body %}
	
	<p class="text-center text-info"> <strong> {{ message }} </strong> </p>
	<p class="text-center"> <a href="{% url 'accounts:user_login' %}"> Login </a> </p>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'todo/_base.html' %}

{% block body %}

	<div class="loginForm">

		<form action="{% url 'accounts:user_login' %}" method="post">
			{% csrf_token %}

      <br><h2 class="text-center"><strong>User Login</strong></h2> <br>

      {% include 'todo/form_snippet.html' with form=login_form %}
      
      <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
          {% if message %}
            <div id="message">
              <strong> {{ message }} </strong>
            </div>
          {% endif %} 
        </div>
        <div class="col-md-4"></div>
      </div> <br>

      <div class="text-center">
        <input type="submit" value="Login" class="btn btn-primary">
      </div>

		</form>
	</div>

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'todo/_base.html' %}

{% block body %}

	<div class="registerForm">

		<form action="{% url 'accounts:user_register' %}" method="post">
			{% csrf_token %}

				<br><h3 class="text-center"> <strong>Register Account</strong> </h3><br>

        {% include 'todo/form_snippet.html' with form=register_form %}

        <div class="row">
          <div class="col-md-4"></div>
          <div class="col-md-4">
            {% if message %}
              <div id="message">
                <strong> {{ message }} </strong>
              </div>
            {% endif %} 
          </div>
          <div class="col-md-4"></div>
        </div> <br>

        <div class="text-center">
          <input type="submit" value="Register" class="btn btn-primary">
        </div>
        
		</form>
	</div>

{% endblock %}