accounts/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^login/$', views.user_login, name='user_login'),
    url(r'^logout/$', views.user_logout, name='user_logout'),
    url(r'^register/$', views.user_register, name='user_register'),
    url(r'^change_password/$', views.change_password, name='change_password'),
]

todo/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # url(r'^login/$', views.user_login, name='user_login'),
    # url(r'^logout/$', views.user_logout, name='user_logout'),
    # url(r'^register/$', views.user_register, name='user_register'),
    url(r'^edit/(\d+)/$', views.edit_todo, name='edit_todo'),
    url(r'^create/$', views.create_todo, name='create_todo'),
    url(r'^details/(\d+)/$', views.todo_details, name='todo_details'),
    # url(r'^changepass/$', views.change_password, name='change_password'),
]

todo_list/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^todo/', include('todo.urls', namespace='todo')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
]

todo/models.py
from django.db import models
from django.contrib.auth.models import User


class Todo(models.Model):
    owner = models.ForeignKey(User)
    content = models.CharField(max_length=150, blank=False)
    created_date = models.DateTimeField('Created date', auto_now_add=True)
    moreinfo = models.CharField(max_length=400, blank=True)

    STATUS = (
        (0, 'In Progress'),
        (1, 'Pending'),
        (2, 'Done'),
        (3, 'Cancelled'),
    )
    status = models.IntegerField(choices=STATUS, default=0)

    PRIORITY = (
        (0, 'Low'),
        (1, 'Medium'),
        (2, 'High'),
    )
    priority = models.IntegerField(choices=PRIORITY, default=0)

    def __unicode__(self):
        return self.content

todo/forms.py
from django import forms
from django.forms import ModelForm
from .models import Todo


# Todo detail form
class DetailForm(ModelForm):
    class Meta:
        model = Todo
        fields = ['priority', 'status', 'moreinfo']
        widgets = {
            'moreinfo': forms.Textarea(attrs={'rows': 10}),
        }

        labels = {
            'moreinfo': 'More Information:',
        }


# New todo form
class NewTodoForm(ModelForm):
    class Meta:
        model = Todo
        fields = ['content', 'priority']
        widgets = {
            'content': forms.Textarea(attrs={'rows': 1, 'cols': 105})
        }

todo/views.py
# Django core imports
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from django.http import HttpResponseRedirect

# Project imports
from .models import Todo
from .forms import DetailForm, NewTodoForm


@login_required(login_url='/accounts/login/')
def index(request):
    """Show login page if user is not logged in, otherwise show todo list for this user"""
    message = ''

    if request.user.is_authenticated():
        current_user = request.user
        todo_list = Todo.objects.filter(owner=current_user) \
            .order_by('status', '-priority', 'content')

        priorities = Todo._meta.get_field('priority').choices
        pdict = dict(priorities)

        stats = Todo._meta.get_field('status').choices
        sdict = dict(stats)

        new_todo_form = NewTodoForm()

        if not todo_list:
            message = 'You have no todo item.'

        return render(request, 'todo/todo_list.html', {
            'todo_list': todo_list,
            'message': message,
            'pdict': pdict,
            'sdict': sdict,
            'new_todo_form': new_todo_form,
        })

###################################################################################################


@login_required
def create_todo(request):
    """Create a new todo item"""

    if request.method == 'POST':
        current_user = request.user
        priority = request.POST['priority']
        content = request.POST['content']

        todo = Todo(owner=current_user, content=content, priority=priority)
        new_todo_form = NewTodoForm(request.POST, instance=todo)

        if new_todo_form.is_valid():
            new_todo_form.save()

            return HttpResponseRedirect('/todo/')

###################################################################################################


@login_required
def edit_todo(request, todo_id):
    """Edit an existing todo item"""

    if request.method == 'POST':
        todo = Todo.objects.get(id=todo_id)
        detail_form = DetailForm(request.POST, instance=todo)

        if detail_form.is_valid():
            detail_form.save()
            return HttpResponseRedirect('/todo/')

###################################################################################################


@login_required
def todo_details(request, todo_id):
    """Show detail information for a todo item"""

    todo = Todo.objects.get(id=todo_id)
    priority_list = Todo._meta.get_field('priority').choices
    status_list = Todo._meta.get_field('status').choices
    detail_form = DetailForm(instance=todo)

    return render(request, 'todo/details.html', {
        'todo': todo,
        'priority_list': priority_list,
        'status_list': status_list,
        'detail_form': detail_form,
    })

###################################################################################################


# @login_required
# def change_password(request):
#     """Change user's password"""

#     message = ''

#     if request.method == 'POST':
#         current_user = request.user
#         change_pass_form = ChangePasswordForm(request.POST)

#         if change_pass_form.is_valid():
#             new_password = change_pass_form.cleaned_data['new_password']
#             re_password = change_pass_form.cleaned_data['re_password']
#             current_password = change_pass_form.cleaned_data['current_password']

#             if not check_password(current_password, current_user.password):
#                 message = "Current password is incorrect."
#             else:
#                 if new_password == re_password:
#                     current_user.set_password(new_password)
#                     current_user.save()
#                     message = 'Your password has been changed.'

#                     return render(request, 'todo/change_password_success.html', {
#                         'message': message
#                     })
#                 else:
#                     message = 'Passwords do not match.'
#     else:
#         change_pass_form = ChangePasswordForm()

#     return render(request, 'todo/change_password.html', {
#         'message': message,
#         'change_pass_form': change_pass_form,
#     })

todo/templates/todo/_base.html
<!DOCTYPE html>
{% load staticfiles %}

<title>Toto Management</title>
<link rel="stylesheet" href="{% static 'todo/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'todo/css/style.css' %}">

<div class="container">
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<a class="navbar-brand" href="{% url 'todo:index' %}">Todo Management System</a>
			{% if user.is_authenticated %}	<!-- if user is logged in, show Logout link -->
				<p class="navbar-text navbar-left">
					<a href="{% url 'accounts:change_password' %}">Change password</a>
				</p>
				<p class="navbar-text navbar-right logout"> Hi, {{ user.username }} -
					<a href="{% url 'accounts:user_logout' %}"> 
						Logout 
					</a> 
				</p>
			{% else %}
				<p class="navbar-text navbar-right register"> 
					<a href="{% url 'accounts:user_register' %}"> Register an account </a> 
				</p>
			{% endif %}
		</div>
	</nav>

	<!-- Sub template -->
	{% block body %} 
	{% endblock %}

	<hr>
	<footer>
		<p class="text-muted text-center credit"> Todo Management - 2015 </p>
	</footer>
</div>

<script src="{% static 'todo/js/jquery.min.js' %}"></script>
<script src="{% static 'todo/js/main.js' %}"></script>

todo/templates/todo/changePassword.html
{% extends 'todo/_base.html' %}

{% block body %}

	<h3 class="text-center"> <strong>Change Password</strong> </h3> <br>

	<form action="{% url 'todo:changePassword' %}" method="post">
		{% csrf_token %}

		{% include "todo/form_snippet.html" with form=change_pass_form %}

    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4">
        {% if message %}
          <div id="message">
            <strong> {{ message }} </strong>
          </div>
        {% endif %} 
      </div>
      <div class="col-md-4"></div>
    </div><br>

		<div class="text-center">
			<input type="submit" value="Change password" class="btn btn-primary">
		</div>
	
	</form>

{% endblock %}

todo/templates/todo/changePasswordSuccess.html
{% extends 'todo/_base.html' %}

{% block body %}
	
	<p class="text-center text-info"> <strong> {{ message }} </strong> </p>
	<p class="text-center"> <a href="{% url 'todo:userLogin' %}"> Login </a> </p>

{% endblock %}

todo/templates/todo/change_password.html
{% extends 'todo/_base.html' %}
{% load widget_tweaks %}

{% block body %}

	<h3 class="text-center"> <strong>Change Password</strong> </h3> <br>

	<form action="{% url 'todo:change_password' %}" method="post">
		{% csrf_token %}

		{% include "todo/form_snippet.html" with form=change_pass_form %}

    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4">
        {% if message %}
          <div id="message">
            <strong> {{ message }} </strong>
          </div>
        {% endif %} 
      </div>
      <div class="col-md-4"></div>
    </div><br>

		<div class="text-center">
			<input type="submit" value="Change password" class="btn btn-primary">
		</div>
	
	</form>

{% endblock %}

todo/templates/todo/change_password_success.html
{% extends 'todo/_base.html' %}

{% block body %}
	
	<p class="text-center text-info"> <strong> {{ message }} </strong> </p>
	<p class="text-center"> <a href="{% url 'todo:user_login' %}"> Login </a> </p>

{% endblock %}

todo/templates/todo/details.html
{% extends 'todo/_base.html' %}
{% load widget_tweaks %}

{% block body %}

<h2 class="text-center"> <strong>{{ todo.content }}</strong></h2>
<br>

<form action="{% url 'todo:edit_todo' todo.id %}" method="post">
{% csrf_token %}

	<div class="form-group">
		<div class="row">
			<div class="col-md-3"></div>
			<div class="col-md-3">
				<label>Created at</label>
				{{ detail_form.created_date.label_tag }}
				<label class="form-control">
					{{ todo.created_date | date:'d/m/Y' }} -
					{{ todo.created_date | date:'h:i A' }}
				</label>  
				<!--{{ detail_form.created_date.label_tag }}
				{{ detail_form.created_date }}-->
			</div>

			<div class="col-md-2">
				{{ detail_form.priority.label_tag }}
				{{ detail_form.priority | attr:"class:form-control" }}
			</div>

			<div class="col-md-2">
				{{ detail_form.status.label_tag }}
				{{ detail_form.status | attr:"class:form-control" }}
			</div>		
			<div class="col-md-2"></div>	
		</div>
		<br>
		<div class="row">
			<div class="col-md-3"></div>

			<div class="col-md-7">
				<!--<label>Additional details</label>
				<textarea class="form-control" rows="6" name='moreinfo'>
					{{ todo.moreinfo }}
				</textarea> -->
				{{ detail_form.moreinfo.label_tag }}
				{{ detail_form.moreinfo | attr:"class:form-control" }}
			</div>

			<div class="col-md-2"></div>
		</div>

	</div>

	<div class="text-center">
		<input type="submit" value="Save" class="btn btn-primary">
	</div>
	
</form>

{% endblock %}

todo/templates/todo/form_snippet.html
{% load widget_tweaks %}

{% for field in form %}
	<div class="form-group">
		<div class="row">
			<div class="col-md-4"></div>
			<div class="col-md-4">
				{{ field.label_tag }}
				{{ field | attr:"class:form-control" }}
			</div>
			<div class="col-md-4"></div>
		</div>
	</div>
{% endfor %}

todo/templates/todo/login.html
{% extends 'todo/_base.html' %}

{% block body %}

	<div class="loginForm">

		<form action="{% url 'todo:user_login' %}" method="post">
			{% csrf_token %}

      <br><h2 class="text-center"><strong>User Login</strong></h2> <br>

      {% include 'todo/form_snippet.html' with form=login_form %}
      
      <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
          {% if message %}
            <div id="message">
              <strong> {{ message }} </strong>
            </div>
          {% endif %} 
        </div>
        <div class="col-md-4"></div>
      </div> <br>

      <div class="text-center">
        <input type="submit" value="Login" class="btn btn-primary">
      </div>

		</form>
	</div>

{% endblock %}

todo/templates/todo/notdone.html
<div id="content">

	{% if todo_list %}
		<input type="button" id="seeAll" value="See all >>" class="btn btn-link btn-sm">
	{% endif %}

	<form class="form">
		{% csrf_token %}
		<div class="container">

			<div class="row top-buffer row-header">
				<div class="col-md-7">
					<p> <strong>Content</strong> </p>
				</div>
				<div class="col-md-2">
					<p> <strong>Created at</strong> </p>
				</div>
				<div class="col-md-1">
					<p> <strong>Priority</strong> </p>
				</div>
				<div class="col-md-2">
					<p> <strong>Status</strong> </p>
				</div>
			</div>

			{% for todo in todo_list %}
				<div class="row top-buffer c_{{todo.status}} o_{{todo.status}}">
					<div class="col-md-7">
						<div class="todoContent"> <a href="{% url 'todo:todo_details' todo.id %}">
							{{todo.content}}</a>
						</div>
					</div>

					<div class="col-md-2">
						{{ todo.created_date | date:'d/m/Y' }} - 
						{{ todo.created_date | date:'h:i A' }}
					</div>

					<div class="col-md-1">
						{{ todo.get_priority_display }}					
					</div>

					<div class="col-md-2 {{ todo.get_status_display }}">
						{{ todo.get_status_display }}		
					</div>
				</div>	
			{% endfor %}

		</div>
	</form>
	<br>

	{% if message %}
		<p class="text-center">{{ message }}</p>
	{% endif %}

</div>

todo/templates/todo/register.html
{% extends 'todo/_base.html' %}

{% block body %}

	<div class="registerForm">

		<form action="{% url 'todo:user_register' %}" method="post">
			{% csrf_token %}

				<br><h3 class="text-center"> <strong>Register Account</strong> </h3><br>

        {% include 'todo/form_snippet.html' with form=register_form %}

        <div class="row">
          <div class="col-md-4"></div>
          <div class="col-md-4">
            {% if message %}
              <div id="message">
                <strong> {{ message }} </strong>
              </div>
            {% endif %} 
          </div>
          <div class="col-md-4"></div>
        </div> <br>

        <div class="text-center">
          <input type="submit" value="Register" class="btn btn-primary">
        </div>
        
		</form>
	</div>

{% endblock %}

todo/templates/todo/todoList.html
{% extends 'todo/_base.html' %}
{% load widget_tweaks %}

{% block body %}

	<div id="createTodoDiv">
		<form class="form-inline" id="createTodoForm" action="{% url 'todo:createTodo' %}" method="post">
			{% csrf_token %}

			<div class="form-group">
				{{ new_todo_form.content.label_tag }}			
				{{ new_todo_form.content | attr:"class:form-control" }}
			</div> &nbsp;&nbsp;

			<div class="form-group">
				{{ new_todo_form.priority.label_tag }}
				{{ new_todo_form.priority | attr:"class:form-control" }}
			</div> &nbsp;&nbsp;

			<input type="submit" value="Create" class="btn btn-primary btn-sm">	
		
		</form>
	</div>

	{% include 'todo/notdone.html' %}

{% endblock %}

todo/templates/todo/todo_list.html
{% extends 'todo/_base.html' %}
{% load widget_tweaks %}

{% block body %}

	<div id="createTodoDiv">
		<form class="form-inline" id="createTodoForm" action="{% url 'todo:create_todo' %}" method="post">
			{% csrf_token %}

			<div class="form-group">
				{{ new_todo_form.content.label_tag }}			
				{{ new_todo_form.content | attr:"class:form-control" }}
			</div> &nbsp;&nbsp;

			<div class="form-group">
				{{ new_todo_form.priority.label_tag }}
				{{ new_todo_form.priority | attr:"class:form-control" }}
			</div> &nbsp;&nbsp;

			<input type="submit" value="Create" class="btn btn-primary btn-sm">	
		
		</form>
	</div>

	{% include 'todo/notdone.html' %}

{% endblock %}